apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  containers:
    - name: nodeapp
      image: gurpartapsingh88/k8simage:latest
      ports:
        - containerPort: 8080
